import { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, Check, Code2, Globe2, MessageCircle, Package, Phone, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { demoProducts, getDemoProducts, money } from '../data/catalog';
import { useAuth } from '../auth/AuthContext';
import { supabase } from '../lib/supabase';

const icons={bot:MessageCircle,public:Globe2,phone:Phone,code:Code2};
function ProductIcon({type}){const Icon=icons[type]||Package;return <Icon size={20}/>}
export default function Storefront(){const {session}=useAuth();const [products,setProducts]=useState([]);const [state,setState]=useState('loading');const [selected,setSelected]=useState(null);useEffect(()=>{let active=true;(async()=>{try{if(supabase){const {data,error}=await supabase.from('products').select('*').eq('active',true).order('created_at');if(error)throw error;const normalized=(data||[]).map(p=>({...p,type:p.type||'script',status:p.active?'active':'inactive'}));if(active){setProducts(normalized.length?normalized:getDemoProducts());setState('ready')}return}if(active){setProducts(getDemoProducts());setState('ready')}}catch{if(active){setProducts(getDemoProducts());setState('error')}}})();return()=>{active=false}},[]);return <><StoreHeader session={session}/><main className="store-page"><section className="store-hero"><div><span className="app-eyebrow"><span/> WhatsApp Bot untuk kebutuhanmu</span><h1>Bot yang bekerja.<br/><em>Kamu yang berkembang.</em></h1><p>Bangun pengalaman WhatsApp yang lebih praktis dengan bot yang stabil, mudah digunakan, dan didukung tim yang siap membantu.</p><div className="app-actions"><a className="dark-btn" href="#produk">Lihat produk ↓</a><a className="light-btn" href="https://wa.me/6281234567890">Hubungi admin <ArrowUpRight size={15}/></a></div></div><div className="app-hero-card"><div className="hero-card-top"><b>✦ starnova</b><span><i/> Online</span></div><div className="hero-card-big">99.9%<strong>Uptime bulan ini</strong></div><div className="hero-chart"><i/><i/><i/><i/><i/><i/><i/></div></div></section><section className="store-products app-section" id="produk"><div className="app-section-heading"><div><span className="app-kicker">Produk Starnova</span><h2>Mulai dari yang<br/><em>kamu butuhkan.</em></h2></div><p>Pilih produk dari katalog yang tersedia. Harga dan status diperbarui dari database.</p></div>{state==='loading'&&<div className="store-state">Memuat produk…</div>}{state==='error'&&<div className="store-state error-state">Produk gagal dimuat. Menampilkan katalog preview.</div>}{state!=='loading'&&products.length===0&&<div className="store-state">Tidak ada produk tersedia saat ini.</div>}<div className="app-products">{products.map(product=><ProductCard key={product.id} product={product} onBuy={()=>setSelected(product)}/>)}</div></section><section className="app-band"><div><span className="app-kicker">Kenapa Starnova</span><h2>Tenang, bot kamu<br/><em>diurus dengan baik.</em></h2></div><div className="benefits"><span><Check/> Setup cepat</span><span><Check/> Stabil setiap hari</span><span><Check/> Update & dokumentasi</span><span><Check/> Bantuan manusia</span></div></section></main><footer className="app-footer"><b>starnova</b><span>Bot yang bekerja untuk kamu.</span><span>© {new Date().getFullYear()} Starnova</span></footer>{selected&&<PurchaseDialog product={selected} session={session} onClose={()=>setSelected(null)}/>}</>}
function StoreHeader({session}){return <header className="app-header"><Link to="/" className="app-brand"><span className="app-mark"><i/><i/><i/></span>starnova</Link><nav><a href="#produk">Produk</a><a href="#keunggulan">Keunggulan</a><a href="#faq">FAQ</a></nav><div className="header-actions">{session?<Link to="/account" className="account-chip">Akun <ArrowUpRight size={14}/></Link>:<Link to="/login" className="header-cta">Masuk <ArrowUpRight size={14}/></Link>}</div></header>}
function ProductCard({product,onBuy}){const price=product.type==='rental'?product.plans?.[0]?.price:product.price;return <article className="catalog-card"><div className="catalog-card-top"><span className={`catalog-icon ${product.icon}`}><ProductIcon type={product.icon}/></span><span className={`availability ${product.status}`}>{product.status==='active'?'Tersedia':'Tidak tersedia'}</span></div><span className="catalog-type">{product.category} · {product.type}</span><h3>{product.name}</h3><p>{product.description}</p><div className="catalog-detail">{product.type==='rental'&&<span>{product.plans?.[0]?.duration} hari</span>}{product.stock!=null&&<span>{product.stock} tersedia</span>}{product.details&&<span>{product.details}</span>}</div><div className="catalog-bottom"><strong>{money(price)}</strong>{product.type==='rental'&&<small>/ {product.plans?.[0]?.duration} hari</small>}<button disabled={product.status!=='active'} onClick={onBuy}>{product.status==='active'?'Beli Sekarang':'Tidak tersedia'} <ArrowUpRight size={14}/></button></div></article>}
function PurchaseDialog({product,session,onClose}){const [duration,setDuration]=useState(product.plans?.[0]?.duration);const [qty,setQty]=useState(1);const [busy,setBusy]=useState(false);const price=product.type==='rental'?(product.plans?.find(p=>p.duration===duration)?.price||0):(product.price||0);async function confirm(){if(!session){window.location.href='/login?next=checkout';return}setBusy(true);if(supabase)await supabase.from('purchases').insert({user_id:session.user.id,product_id:product.id,product_name:product.name,amount:price*qty,status:'pending'});setBusy(false);onClose()}return <div className="purchase-backdrop"><div className="purchase-dialog"><button className="modal-x" onClick={onClose}><X size={18}/></button><span className="app-kicker">Konfirmasi pembelian</span><h2>{product.name}</h2><p>{product.description}</p><div className="purchase-info"><span>Jenis<strong>{product.type}</strong></span><span>Harga<strong>{money(price)}</strong></span>{product.duration&&<span>Durasi<strong>{product.duration} hari</strong></span>}</div>{product.type==='rental'&&<label className="duration-label">Durasi{<select value={duration} onChange={e=>setDuration(Number(e.target.value))}>{product.plans.map(plan=><option key={plan.duration} value={plan.duration}>{plan.duration} Hari — {money(plan.price)}</option>)}</select>}</label>}{product.type!=='rental'&&<label className="duration-label">Quantity<input type="number" min="1" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)))}/></label>}<div className="purchase-total"><span>Total</span><strong>{money(price*qty)}</strong></div><button className="dark-btn full" onClick={confirm} disabled={busy}>{busy?'Memproses…':session?'Konfirmasi pembelian':'Masuk untuk membeli'} <ArrowUpRight size={15}/></button>{!session&&<small className="secure-note">Kamu wajib login sebelum membuat pesanan.</small>}</div></div>}
