import { useEffect, useState } from 'react';
import { BrowserRouter, Routes, Route, Link, Navigate, useNavigate } from 'react-router-dom';
import { ArrowUpRight, Check, ChevronDown, CircleHelp, LayoutDashboard, LogOut, Menu, Package, ShieldCheck, Sparkles, UserRound, X } from 'lucide-react';
import { AuthProvider, useAuth } from './auth/AuthContext';
import { supabase } from './lib/supabase';
import './app.css';
import { LegacyLanding, LegacyAdmin } from './LegacyPages';

const products = [
  { id:'private', icon:'bot', name:'Sewa Bot', plan:'Private', price:'Rp 79.000', description:'Bot siap pakai untuk grup kecil dengan kontrol yang lebih personal.' },
  { id:'public', icon:'activity', name:'Sewa Bot', plan:'Public', price:'Rp 149.000', description:'Bot siap pakai tanpa batas jumlah anggota grup.' },
  { id:'jadi-bot', icon:'bot', name:'Jadi Bot', plan:'Nomor milikmu', price:'Rp 99.000', description:'Hubungkan nomor WhatsApp kamu tanpa mengganti nomor utama.' },
  { id:'script', icon:'code', name:'Beli Script', plan:'Source code + License', price:'Rp 899.000', description:'Source code bot lengkap dengan License Key untuk aktivasi.' },
];

function Header(){ const {session,signOut}=useAuth(); const [open,setOpen]=useState(false); return <header className="app-header"><Link to="/" className="app-brand"><span className="app-mark"><i/><i/><i/></span>starnova</Link><nav><a href="#produk">Produk</a><a href="#keunggulan">Keunggulan</a><a href="#faq">FAQ</a></nav><div className="header-actions">{session ? <><Link to="/account" className="account-chip"><UserRound size={14}/> Akun</Link><button className="ghost-action" onClick={signOut}><LogOut size={14}/></button></> : <Link to="/login" className="header-cta">Masuk <ArrowUpRight size={14}/></Link>}<button className="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobile-nav"><a href="#produk" onClick={()=>setOpen(false)}>Produk</a><a href="#keunggulan" onClick={()=>setOpen(false)}>Keunggulan</a><a href="#faq" onClick={()=>setOpen(false)}>FAQ</a></div>}</header> }

function Landing(){ const {session}=useAuth(); const [selected,setSelected]=useState(null); return <><Header/><main><section className="app-hero"><div><span className="app-eyebrow"><span/> WhatsApp Bot untuk kebutuhanmu</span><h1>Bot yang bekerja.<br/><em>Kamu yang berkembang.</em></h1><p>Bangun pengalaman WhatsApp yang lebih praktis dengan bot yang stabil, mudah digunakan, dan didukung tim yang benar-benar siap membantu.</p><div className="app-actions"><a className="dark-btn" href="#produk">Lihat produk ↓</a><a className="light-btn" href="https://wa.me/6281234567890">Hubungi admin <ArrowUpRight size={15}/></a></div></div><div className="app-hero-card"><div className="hero-card-top"><b><Sparkles size={14}/> starnova</b><span><i/> Online</span></div><div className="hero-card-big">24.892<strong>Total pesan diproses</strong></div><div className="hero-chart"><i/><i/><i/><i/><i/><i/><i/></div><div className="hero-card-bottom"><span>Uptime bulan ini</span><b>99.9%</b></div></div></section><section className="app-section" id="produk"><div className="app-section-heading"><div><span className="app-kicker">Produk Starnova</span><h2>Mulai dari yang<br/><em>kamu butuhkan.</em></h2></div><p>Pilih layanan yang sesuai dengan cara kerja kamu. Semua dibuat agar bisa langsung digunakan tanpa langkah yang rumit.</p></div><div className="app-products">{products.map(p=><article className="app-product" key={p.id}><span className="product-symbol">{p.icon==='bot'?<CircleHelp size={19}/>:p.icon==='activity'?<Sparkles size={19}/>:p.icon==='code'?<Package size={19}/>:<CircleHelp size={19}/>}</span><span className="app-kicker">{p.plan}</span><h3>{p.name}</h3><p>{p.description}</p><div className="product-price">{p.price}<small>/ mulai</small></div><button className="product-buy" onClick={()=>setSelected(p)}>Pilih produk <ArrowUpRight size={14}/></button></article>)}</div></section><section className="app-band" id="keunggulan"><div><span className="app-kicker">Kenapa Starnova</span><h2>Tenang, bot kamu<br/><em>diurus dengan baik.</em></h2></div><div className="benefits"><span><Check/> Setup cepat</span><span><Check/> Stabil setiap hari</span><span><Check/> Update & dokumentasi</span><span><Check/> Bantuan manusia</span></div></section><section className="app-section faq" id="faq"><span className="app-kicker">Punya pertanyaan?</span><h2>Jawaban yang <em>kamu cari.</em></h2>{['Apa perbedaan Private dan Public?','Berapa lama proses aktivasi?','Apakah script mendapatkan update?'].map((q,i)=><details key={q} open={i===0}><summary>{q}<ChevronDown size={17}/></summary><p>Private cocok untuk grup kecil, sedangkan Public tidak memiliki batas anggota. Aktivasi biasanya selesai setelah pembayaran dikonfirmasi admin.</p></details>)}</section></main><footer className="app-footer"><b>starnova</b><span>Bot yang bekerja untuk kamu.</span><span>© 2025 Starnova</span></footer>{selected&&<PurchaseModal product={selected} onClose={()=>setSelected(null)} loggedIn={Boolean(session)}/>}</> }

function PurchaseModal({product,onClose,loggedIn}){ const {session}=useAuth(); const navigate=useNavigate(); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); async function buy(){ if(!loggedIn){navigate('/login?next=checkout');return} setBusy(true); if(supabase){ const numericAmount=Number(product.price.replace(/[^0-9]/g,'')); await supabase.from('purchases').insert({user_id:session.user.id,product_id:product.id,product_name:`${product.name} — ${product.plan}`,amount:numericAmount}); } setBusy(false);setDone(true); } return <div className="app-modal-backdrop"><div className="app-modal"><button className="modal-x" onClick={onClose}><X size={18}/></button>{done?<><div className="success-icon"><Check/></div><h2>Pesanan diterima</h2><p>Admin akan menghubungi kamu untuk proses aktivasi produk.</p><button className="dark-btn" onClick={onClose}>Selesai</button></>:<><span className="app-kicker">Konfirmasi produk</span><h2>{product.name} <em>— {product.plan}</em></h2><p>{product.description}</p><div className="checkout-line"><span>Total</span><strong>{product.price}</strong></div><button className="dark-btn full" onClick={buy} disabled={busy}>{busy?'Memproses…':loggedIn?'Lanjutkan pembelian':'Masuk untuk membeli'} <ArrowUpRight size={15}/></button><small className="secure-note"><ShieldCheck size={13}/> Pembelian aman dan tercatat di akunmu</small></>}</div></div> }

function Login({mode='signin'}){
  const isSignup=mode==='signup';
  const {signInWithOtp,verifyOtp,signInWithGoogle,session,configured}=useAuth();
  const navigate=useNavigate();
  const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [otp,setOtp]=useState(''); const [step,setStep]=useState('email'); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  if(session)return <Navigate to="/" replace/>;
  async function requestOtp(e){e.preventDefault();setError('');setMessage('');setBusy(true);try{await signInWithOtp(email,name);setStep('otp');setMessage('Kode OTP sudah dikirim ke email kamu.')}catch(err){setError(err.message)}finally{setBusy(false)}}
  async function submitOtp(e){e.preventDefault();setError('');setBusy(true);try{await verifyOtp(email,otp);navigate('/')}catch(err){setError(err.message)}finally{setBusy(false)}}
  async function google(){setError('');try{await signInWithGoogle()}catch(err){setError(err.message)}}
  return <div className="auth-screen"><Link to="/" className="app-brand"><span className="app-mark"><i/><i/><i/></span>starnova</Link><div className="auth-card"><span className="app-kicker">{isSignup?'Buat akun baru':'Selamat datang kembali'}</span><h1>{step==='email'?(isSignup?'Mulai bersama Starnova.':'Masuk ke akunmu.'):'Masukkan kode OTP.'}</h1><p>{step==='email'?(isSignup?'Daftar dengan OTP email atau Google. Tidak perlu password.':'Masuk dengan OTP email atau Google untuk melanjutkan pembelian.'):'Cek inbox kamu dan masukkan 6 digit kode verifikasi.'}</p>{!configured&&<div className="config-note">Supabase belum tersambung. Tambahkan environment variable di Vercel.</div>}{step==='email'?<><button className="google-btn" type="button" onClick={google}><span className="google-g">G</span> {isSignup?'Daftar dengan Google':'Lanjutkan dengan Google'}</button><div className="auth-divider"><span>atau gunakan email</span></div><form onSubmit={requestOtp}>{isSignup&&<label>Nama<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Nama lengkap"/></label>}<label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="nama@email.com"/></label>{error&&<div className="form-error">{error}</div>}<button className="dark-btn full" disabled={busy}>{busy?'Mengirim…':isSignup?'Kirim kode pendaftaran':'Kirim kode OTP'} <ArrowUpRight size={15}/></button></form></>:<form onSubmit={submitOtp}><label>Email<input type="email" value={email} readOnly/></label><label>Kode OTP<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength="6" required value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} placeholder="000000"/></label>{message&&<div className="form-success">{message}</div>}{error&&<div className="form-error">{error}</div>}<button className="dark-btn full" disabled={busy}>{busy?'Memverifikasi…':isSignup?'Verifikasi & buat akun':'Verifikasi & masuk'} <ArrowUpRight size={15}/></button><button type="button" className="switch-auth" onClick={()=>{setStep('email');setOtp('');setError('')}}>Gunakan email lain</button></form>}<div className="auth-switch-link">{isSignup?'Sudah punya akun? ':'Belum punya akun? '}<Link to={isSignup?'/login':'/signup'}>{isSignup?'Sign in':'Sign up'}</Link></div><small className="auth-terms">Dengan melanjutkan, kamu menyetujui ketentuan penggunaan Starnova.</small></div></div>
}
function ProtectedAdmin(){const {profile,loading}=useAuth();if(loading)return <div className="loading-screen">Memuat workspace…</div>;if(!profile||!['owner','admin'].includes(profile.role))return <Navigate to="/" replace/>;return <div className="react-admin"><aside><Link to="/" className="app-brand"><span className="app-mark"><i/><i/><i/></span>starnova <small>ADMIN</small></Link><p className="admin-label">WORKSPACE</p><Link className="admin-link active" to="/admin"><LayoutDashboard size={15}/> Overview</Link><Link className="admin-link" to="/admin/users"><UserRound size={15}/> User</Link><Link className="admin-link" to="/admin/products"><Package size={15}/> Produk</Link><Link className="admin-link" to="/admin/roles"><ShieldCheck size={15}/> Role & akses</Link><div className="admin-aside-bottom"><span>{profile.email}</span><button onClick={()=>supabase.auth.signOut()}><LogOut size={14}/> Keluar</button></div></aside><div className="react-admin-main"><div className="react-admin-top"><span>Workspace / <b>Overview</b></span><span className="admin-status"><i/> Live data</span></div><div className="react-admin-content"><div className="admin-title"><div><span className="app-kicker">Dashboard</span><h1>Selamat pagi, {profile.name||'Admin'} <Sparkles size={18}/></h1><p>Kelola user, produk, pesanan, dan akses dari satu workspace.</p></div><Link className="dark-btn" to="/admin/products">Kelola produk <ArrowUpRight size={14}/></Link></div><div className="admin-metrics"><div><span>Total revenue</span><strong>Rp 24.8 jt</strong><small>↗ 12,8% dari bulan lalu</small></div><div><span>Pengguna aktif</span><strong>128</strong><small>↗ 8,4% dari bulan lalu</small></div><div><span>Pesanan bulan ini</span><strong>86</strong><small>↗ 6,2% dari bulan lalu</small></div><div><span>Bot aktif</span><strong>112</strong><small>87,5% dari total user</small></div></div><div className="admin-panels"><div className="admin-panel revenue-live"><h2>Ringkasan revenue</h2><p>Pendapatan 6 bulan terakhir</p><div className="live-bars">{[48,61,54,77,68,91].map((v,i)=><div key={i}><i style={{height:`${v}%`}}/><span>{['Mar','Apr','Mei','Jun','Jul','Agu'][i]}</span></div>)}</div></div><div className="admin-panel"><h2>Aktivitas terbaru</h2><p>Update workspace secara live</p><div className="activity-item"><i/><div><b>Pembayaran baru</b><small>Dimas Nugraha membeli Sewa Bot</small></div><time>2m</time></div><div className="activity-item"><i/><div><b>User baru terdaftar</b><small>Nadia Putri membuat akun</small></div><time>18m</time></div><div className="activity-item"><i/><div><b>Bot aktif</b><small>Private Bot siap digunakan</small></div><time>32m</time></div></div></div></div></div></div>}
function ProfileNameGate(){const {session,profile,updateUsername,checkUsername}=useAuth();const [username,setUsername]=useState('');const [availability,setAvailability]=useState(null);const [busy,setBusy]=useState(false);useEffect(()=>{let cancelled=false;const value=username.trim().toLowerCase();if(!/^[a-z0-9_]{3,24}$/.test(value)){setAvailability(value?'invalid':null);return}const timer=setTimeout(async()=>{try{const ok=await checkUsername(value);if(!cancelled)setAvailability(ok)}catch{if(!cancelled)setAvailability(null)}},300);return()=>{cancelled=true;clearTimeout(timer)}},[username,checkUsername]);if(!session||!profile||profile.username)return null;async function save(e){e.preventDefault();if(availability!==true)return;setBusy(true);try{await updateUsername(username)}finally{setBusy(false)}}return <div className="profile-gate"><div className="profile-gate-card"><span className="app-kicker">Welcome to Starnova</span><h2>Pilih <em>username</em> kamu.</h2><p>Username ini akan menjadi identifier akun dan digunakan untuk dashboard Starnova.</p><form onSubmit={save}><label>Username<div className="username-input"><span>@</span><input autoFocus required minLength="3" maxLength="24" pattern="[a-z0-9_]+" value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} placeholder="username"/></div></label>{availability===true&&<div className="username-ok">✓ Username tersedia</div>}{availability===false&&<div className="username-error">✕ Username sudah digunakan</div>}{availability==='invalid'&&<div className="username-error">Gunakan 3–24 karakter: huruf kecil, angka, atau underscore.</div>}<button className="dark-btn full" disabled={busy||availability!==true}>{busy?'Menyimpan…':'Lanjutkan'} <ArrowUpRight size={15}/></button></form></div></div>}
function NotFound(){return <div className="not-found-screen"><div className="not-found-orb"><CircleHelp size={34}/></div><span className="app-kicker">Starnova / 404</span><h1>Halaman ini tidak<br/><em>ditemukan.</em></h1><p>Alamat yang kamu buka mungkin sudah dipindahkan atau tidak tersedia.</p><div className="not-found-actions"><Link to="/" className="dark-btn">Kembali ke beranda <ArrowUpRight size={15}/></Link><Link to="/login" className="light-btn">Masuk ke akun</Link></div></div>}
function App(){return <AuthProvider><BrowserRouter><Routes><Route path="/" element={<LegacyLanding/>}/><Route path="/login" element={<Login mode="signin"/>}/><Route path="/signup" element={<Login mode="signup"/>}/><Route path="/account" element={<Navigate to="/login" replace/>}/><Route path="/admin/*" element={<LegacyAdmin/>}/><Route path="*" element={<NotFound/>}/></Routes><ProfileNameGate/></BrowserRouter></AuthProvider>}
export default App;
